### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by amccool** [Recognos/Metrics.NET#19]
looks like etishor was using Appveyor for builds.

What can I do to help convert the Recognos repo to have appveyor builds?

**Comment by hinteadan** [comment]
Hi,
First of all thank you for the interest!
He was using both AppVeyor and Travis CI, but I think **we**'ll have to take care of them because they need access to the repo to register web-hooks upon **git push**-es so they know when to trigger the build.
I say "_I think_" because I didn't use any of them before, I just know that's how CI systems usually work.

Other than that no conversion is needed, we just need to configure new AppVeyor and Travis projects to run **build.bat** on this repo. And of course update the URLs in README.md.

**Comment by hinteadan** [comment]
I configured AppVeyor, Travis and Git Stats and updated the badges in README.md. Will close this issue.
