### ISSUE TITLE
Question: how to control which metrics are shown by default

### ISSUE THREAD

**Issue by dariusdamalakas** [Recognos/Metrics.NET#8]
Hi,

Sorry if this is an easy question, but I could not find my answer anywhere. Is is possible to control which metrics are pre-selected be default when we load http endpoint for metrics visualisation? 

By default all timers are pre-selected, and this causes the browser to crash/unresponsive, so ideally we'd like to show none by default. What options are there available to control this?

Thanks

**Comment by PaulParau** [comment]
Hi, sorry for the late reply.

Yes, we are aware that the visualization app is slow when loading a large amount of metrics. There are currently no options to configure this behavior, but since version 3.3-pre (prerelease) no metrics are shown by default for this precise reason.

This change has not yet made it's way to the stable release channel, but we aim to release a new stable version containing this change (and other improvements) in the near future. So right now, switching to the prerelease version would solve this issue (if using a prerelease package is acceptable in your project).

Hope this helps,
Paul

**Comment by dariusdamalakas** [comment]
Thanks @PaulParau ! I guess we can live with this for the time being and wait for 3.3 release. It's good to know there is an option if we desperately need this.
